backend:
  name: github
  repo: ParaguayNoticias/noticias_de_la_actualidad
  branch: master
  site_domain: "https://noticias-de-la-actualidad.vercel.app/"
  commit_messages:
    create: "Creada noticia: {{slug}}"
    update: "Actualizada noticia: {{slug}}"
    delete: "Eliminada noticia: {{slug}}"

media_folder: "public/uploads"
public_folder: "/uploads"
collections_folder: "content"
collections:
  - name: "noticias"
    label: "Noticias"
    folder: "noticias"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Resumen", name: "resumen", widget: "text" }
      - { label: "Contenido", name: "contenido", widget: "markdown" }
      - label: "Categoría"
        name: "categoria"
        widget: "select"
        options:
          - { label: "Política", value: "Política" }
          - { label: "Deportes", value: "Deportes" }
          - { label: "Tecnología", value: "Tecnología" }
          - { label: "Cultura", value: "Cultura" }
          - { label: "Nacionales", value: "Nacionales" }
          - { label: "Internacionales", value: "Internacionales" }
        default: "nacionales"
      - label: "Imagen Principal"
        name: "imagen"
        widget: "image"
        media_library: 
          config: 
            cloud_name: process.env.CLOUDINARY_NAME  
            api_key: process.env.CLOUDINARY_KEY 
            multiple: false
      - { label: "Destacada", name: "destacada", widget: "boolean", default: false }
      - { label: "Autor", name: "autor", widget: "string", required: false }
      - { label: "Slug", name: "slug", widget: "string", pattern: ["^[a-z0-9-]+$", "Solo minúsculas, números y guiones"] }