backend:
  name: github
  repo: ParaguayNoticias/noticias_de_la_actualidad
  branch: master
  site_domain: "localhost:3000"
  commit_messages:
    create: "Creada noticia: {{slug}}"
    update: "Actualizada noticia: {{slug}}"
    delete: "Eliminada noticia: {{slug}}"

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "content/noticias"
    create: true
    # CAMBIO CLAVE: Usar solo fecha y slug corto
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Resumen", name: "resumen", widget: "text" }
      - { label: "Imagen Principal", name: "imagen", widget: "image" }
      - { label: "Contenido", name: "contenido", widget: "markdown" }
      - label: "Categoría"
        name: "categoria"
        widget: "select"
        options:
          - { label: "Política", value: "Política" }
          - { label: "Deportes", value: "Deportes" }
          - { label: "Tecnología", value: "Tecnología" }
          - { label: "Cultura", value: "Cultura" }
          - { label: "Nacionales", value: "Nacionales" }
          - { label: "Internacionales", value: "Internacionales" }
      - { label: "Destacada", name: "destacada", widget: "boolean", default: false }
      - { 
          label: "Slug (URL corta)", 
          name: "slug", 
          widget: "string", 
          pattern: ["^[a-z0-9-]{5,60}$", "Solo minúsculas, números y guiones (5-60 caracteres)"],
          hint: "Identificador corto para la URL (ej: pensiones-adultos-mayores)" 
        }