backend:
  name: github
  repo: ParaguayNoticias/noticias_de_la_actualidad
  branch: master
  site_domain: "localhost:3000"
  commit_messages:
    create: "Creada noticia: {{slug}}"
    update: "Actualizada noticia: {{slug}}"
    delete: "Eliminada noticia: {{slug}}"

# Configuración de medios (Cloudinary)
media_folder: ""  
public_folder: "" 
media_library:
  name: cloudinary
  config:
    cloud_name: process.env.CLOUDINARY_NAME
    api_key: process.env.CLOUDINARY_KEY
    multiple: false

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "cms-content/noticias"  
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Resumen", name: "resumen", widget: "text" }
      - label: "Imagen Principal"
        name: "imagen_url"
        widget: "image"
        media_library: 
          config: 
            cloud_name: process.env.CLOUDINARY_NAME
            api_key: process.env.CLOUDINARY_KEY
            multiple: false
      - { label: "Contenido", name: "contenido", widget: "markdown" }
      - label: "Categoría"
        name: "categoria"
        widget: "select"
        options:
          - { label: "Política", value: "Política" }
          - { label: "Deportes", value: "Deportes" }
          - { label: "Tecnología", value: "Tecnología" }
          - { label: "Cultura", value: "Cultura" }
          - { label: "Nacionales", value: "Nacionales" }
          - { label: "Internacionales", value: "Internacionales" }
      - { label: "Destacada", name: "destacada", widget: "boolean", default: false }
      - { 
          label: "Slug (URL corta)", 
          name: "slug", 
          widget: "string", 
          pattern: ["^[a-z0-9-]{5,60}$", "Solo minúsculas, números y guiones (5-60 caracteres)"],
          hint: "Identificador corto para la URL (ej: pensiones-adultos-mayores)" 
        }
      - { label: "Autor", name: "autor", widget: "string" }
      - {label: "Fecha de Publicación",
        name: "fecha",
        widget: "datetime",
        format: "YYYY-MM-DD HH:mm",
        date_format: "YYYY-MM-DD",
        time_format: "HH:mm",
        hint: "Fecha de publicación (dejar vacío para fecha actual)"}